name: P123 API Client Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.5.0
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[test]"
      
      - name: Run quality checks
        run: |
          source .venv/bin/activate
          make quality
      
      # CI Always uses existing cassettes - never makes real API calls
      - name: Run tests with existing cassettes
        run: |
          echo "Running tests in CI with VCR_RECORD_MODE=none (using existing cassettes only)"
          source .venv/bin/activate
          python -m pytest tests/
        env:
          VCR_ENABLED: "true"
          VCR_RECORD_MODE: "none"
      
      # If tests fail because cassettes are missing or outdated, we provide a helpful error message
      - name: Handle cassette-related failures
        if: failure()
        run: |
          echo "::warning::Tests failed - this may be because cassettes are missing or outdated"
          echo "::warning::To update cassettes, run locally with: VCR_RECORD_MODE=all pytest tests/"
          echo "::warning::Then commit the updated cassette files"
          exit 1 